#!/bin/bash
w > users.log;
if echo users.log | grep -q "droessmj"
	then echo "Michaeld is online"
	else lastlog -u droessmj
fi
if echo users.log | grep -q "savidespd"
	then echo "Paul S is online"
	else lastlog -u savidespd
fi
